#!/usr/bin/env python3
"""Run matched A/B accuracy and throughput checks for demag extrapolation.

The two cases run in separate processes from identical generated mx3 input.
Accuracy is measured from the fixed-dt average-magnetization trajectory and
total energy. Performance is measured without per-step output, so output-side
exact demag queries do not contaminate the timing.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import statistics
import subprocess
import tempfile
from pathlib import Path


RESULT_RE = re.compile(
    r"DEMAG_AB_RESULT\s+wall\s+([0-9.eE+-]+)\s+exact\s+([0-9]+)\s+extrapolated\s+([0-9]+)"
)


def input_text(*, enabled: bool, nx: int, ny: int, steps: int, dt: float, accuracy: bool) -> str:
    table = "TableAdd(E_total)\nTableAutoSave(FixDt)" if accuracy else ""
    return f"""// Generated by bench/demag-extrap/run_ab.py
SetGridSize({nx}, {ny}, 1)
SetCellSize(4e-9, 4e-9, 4e-9)
Msat = 800e3
Aex = 13e-12
alpha = 0.02
m = uniform(1, 0.1, 0.01)
B_ext = vector(-20e-3, 4e-3, 1e-3)
SetSolver(5)
FixDt = {dt:.17g}
DemagExtrapolation = {str(enabled).lower()}
{table}
start := now()
Steps({steps})
wall := since(start).Seconds()
print("DEMAG_AB_RESULT", "wall", wall, "exact", GetDemagExactEvals(), "extrapolated", GetDemagExtrapolatedEvals())
"""


def run_case(binary: Path, root: Path, label: str, text: str) -> dict[str, object]:
    script = root / f"{label}.mx3"
    out = root / f"{label}.out"
    script.write_text(text)
    proc = subprocess.run(
        [str(binary), "-f", "-o", str(out), str(script)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    (root / f"{label}.log").write_text(proc.stdout)
    if proc.returncode:
        raise RuntimeError(f"{label} failed ({proc.returncode}); see {root / f'{label}.log'}")
    match = RESULT_RE.search(proc.stdout)
    if not match:
        raise RuntimeError(f"missing result marker for {label}; see {root / f'{label}.log'}")
    return {
        "wall_s": float(match.group(1)),
        "exact": int(match.group(2)),
        "extrapolated": int(match.group(3)),
        "out": out,
    }


def read_table(path: Path) -> tuple[list[str], list[list[float]]]:
    with path.open(newline="") as handle:
        rows = [line.strip() for line in handle if line.strip()]
    header = rows[0].lstrip("# ").split("\t")
    values = [[float(value) for value in row.split("\t")] for row in rows[1:]]
    return header, values


def find_column(header: list[str], prefix: str) -> int:
    for i, name in enumerate(header):
        if name == prefix or name.startswith(prefix + " "):
            return i
    raise KeyError(f"column {prefix!r} not found in {header!r}")


def compare_trajectories(a_path: Path, b_path: Path) -> dict[str, float]:
    ah, av = read_table(a_path)
    bh, bv = read_table(b_path)
    if ah != bh or len(av) != len(bv):
        raise RuntimeError("A/B table grids differ")
    columns = [find_column(ah, name) for name in ("mx", "my", "mz")]
    energy = find_column(ah, "E_total")
    vector_errors: list[float] = []
    energy_abs: list[float] = []
    energy_rel: list[float] = []
    energy_scale = max((abs(row[energy]) for row in av), default=0.0)
    for ar, br in zip(av, bv):
        vector_errors.append(math.sqrt(sum((ar[c] - br[c]) ** 2 for c in columns)))
        denom = max(abs(ar[energy]), 1e-30)
        difference = abs(ar[energy] - br[energy])
        energy_abs.append(difference)
        energy_rel.append(difference / denom)
    energy_max_abs = max(energy_abs, default=0.0)
    energy_rms_abs = math.sqrt(sum(value * value for value in energy_abs) / max(len(energy_abs), 1))
    return {
        "trajectory_max_abs": max(vector_errors, default=0.0),
        "trajectory_rms_abs": math.sqrt(
            sum(value * value for value in vector_errors) / max(len(vector_errors), 1)
        ),
        "energy_max_rel": max(energy_rel, default=0.0),
        "energy_rms_rel": math.sqrt(
            sum(value * value for value in energy_rel) / max(len(energy_rel), 1)
        ),
        "energy_max_abs_J": energy_max_abs,
        "energy_rms_abs_J": energy_rms_abs,
        "energy_max_normalized": energy_max_abs / max(energy_scale, 1e-30),
        "energy_rms_normalized": energy_rms_abs / max(energy_scale, 1e-30),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mumax", type=Path, required=True, help="mumax3 binary to test")
    parser.add_argument("--out", type=Path, help="directory for scripts, logs and outputs")
    parser.add_argument("--nx", type=int, default=512)
    parser.add_argument("--ny", type=int, default=512)
    parser.add_argument("--steps", type=int, default=200)
    parser.add_argument("--dt", type=float, default=1e-13)
    parser.add_argument("--accuracy-nx", type=int, default=128)
    parser.add_argument("--accuracy-ny", type=int, default=64)
    parser.add_argument("--accuracy-steps", type=int, default=200)
    parser.add_argument("--repeats", type=int, default=3)
    args = parser.parse_args()

    root = args.out or Path(tempfile.mkdtemp(prefix="mumax3-demag-extrap-ab."))
    root.mkdir(parents=True, exist_ok=True)
    binary = args.mumax.resolve()

    accuracy_results = {}
    for enabled, label in ((False, "accuracy_exact"), (True, "accuracy_extrap")):
        accuracy_results[label] = run_case(
            binary,
            root,
            label,
            input_text(
                enabled=enabled,
                nx=args.accuracy_nx,
                ny=args.accuracy_ny,
                steps=args.accuracy_steps,
                dt=args.dt,
                accuracy=True,
            ),
        )
    errors = compare_trajectories(
        Path(accuracy_results["accuracy_exact"]["out"]) / "table.txt",
        Path(accuracy_results["accuracy_extrap"]["out"]) / "table.txt",
    )

    timings: dict[str, list[float]] = {"exact": [], "extrap": []}
    counts: dict[str, dict[str, int]] = {}
    for repeat in range(args.repeats):
        for enabled, label in ((False, "exact"), (True, "extrap")):
            key = f"perf_{label}_{repeat}"
            result = run_case(
                binary,
                root,
                key,
                input_text(
                    enabled=enabled,
                    nx=args.nx,
                    ny=args.ny,
                    steps=args.steps,
                    dt=args.dt,
                    accuracy=False,
                ),
            )
            timings[label].append(float(result["wall_s"]))
            counts[label] = {"exact": int(result["exact"]), "extrapolated": int(result["extrapolated"])}

    exact_median = statistics.median(timings["exact"])
    extrap_median = statistics.median(timings["extrap"])
    report = {
        "mesh": [args.nx, args.ny, 1],
        "steps": args.steps,
        "dt_s": args.dt,
        "timings_s": timings,
        "median_exact_s": exact_median,
        "median_extrap_s": extrap_median,
        "speedup": exact_median / extrap_median,
        "demag_counts_last_repeat": counts,
        "accuracy_mesh": [args.accuracy_nx, args.accuracy_ny, 1],
        "accuracy_steps": args.accuracy_steps,
        **errors,
    }
    (root / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))
    print(f"artifacts: {root}")


if __name__ == "__main__":
    main()
