#!/usr/bin/env python3
"""Cross-solver validation with geometry, regions and periodic boundaries."""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import re
import subprocess
import tempfile
from pathlib import Path


RESULT_RE = re.compile(
    r"DEMAG_MATRIX_RESULT\s+wall\s+([0-9.eE+-]+)\s+energy\s+([0-9.eE+-]+)"
    r"\s+exact\s+([0-9]+)\s+extrapolated\s+([0-9]+)"
)
STATUS_RE = re.compile(r"DEMAG_MATRIX_STATUS\s+(.+)")


def load_ovf_reader():
    path = Path(__file__).with_name("run_std4_adaptive.py")
    spec = importlib.util.spec_from_file_location("demag_std4_helpers", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.read_binary4_ovf


READ_OVF = load_ovf_reader()


def script_text(*, enabled: bool, solver: int, steps: int, dt: float) -> str:
    return f"""// Geometry/region/PBC validation generated by validate_matrix.py.
SetGridSize(64, 48, 1)
SetCellSize(4e-9, 4e-9, 4e-9)
SetPBC(1, 1, 0)
SetGeom(Ellipse(240e-9, 176e-9))
DefRegion(1, Circle(80e-9))
Msat = 800e3
Msat.SetRegion(1, 620e3)
Aex = 13e-12
alpha = 0.02
m = vortex(1, 1)
B_ext = vector(-18e-3, 5e-3, 2e-3)
SetSolver({solver})
FixDt = {dt:.17g}
DemagExtrapolation = {str(enabled).lower()}
start := now()
Steps({steps})
wall := since(start).Seconds()
energy := E_total.get()
Save(m)
print("DEMAG_MATRIX_RESULT", "wall", wall, "energy", energy, "exact", GetDemagExactEvals(), "extrapolated", GetDemagExtrapolatedEvals())
print("DEMAG_MATRIX_STATUS", GetDemagExtrapolationStatus())
"""


def run(binary: Path, root: Path, label: str, text: str) -> dict[str, object]:
    script = root / f"{label}.mx3"
    out = root / f"{label}.out"
    script.write_text(text)
    proc = subprocess.run(
        [str(binary), "-f", "-o", str(out), str(script)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    (root / f"{label}.log").write_text(proc.stdout)
    if proc.returncode:
        raise RuntimeError(f"{label} failed ({proc.returncode}); see {root / f'{label}.log'}")
    match = RESULT_RE.search(proc.stdout)
    if not match:
        raise RuntimeError(f"missing result marker for {label}; see {root / f'{label}.log'}")
    status = STATUS_RE.search(proc.stdout)
    return {
        "wall_s": float(match.group(1)),
        "energy_J": float(match.group(2)),
        "exact": int(match.group(3)),
        "extrapolated": int(match.group(4)),
        "status": status.group(1).strip() if status else "missing",
        "out": out,
    }


def compare_fields(a_path: Path, b_path: Path) -> dict[str, float]:
    a = READ_OVF(a_path)
    b = READ_OVF(b_path)
    if len(a) != len(b):
        raise RuntimeError("OVF grids differ")
    errors = [math.sqrt(sum((x - y) ** 2 for x, y in zip(av, bv))) for av, bv in zip(a, b)]
    return {
        "field_mean_abs_error": sum(errors) / max(len(errors), 1),
        "field_rms_abs_error": math.sqrt(sum(value * value for value in errors) / max(len(errors), 1)),
        "field_max_abs_error": max(errors, default=0.0),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mumax", type=Path, required=True)
    parser.add_argument("--out", type=Path)
    parser.add_argument("--steps", type=int, default=200)
    parser.add_argument("--dt", type=float, default=1e-13)
    args = parser.parse_args()
    root = args.out or Path(tempfile.mkdtemp(prefix="mumax3-demag-matrix."))
    root.mkdir(parents=True, exist_ok=True)
    binary = args.mumax.resolve()

    report: dict[str, object] = {
        "steps": args.steps,
        "dt_s": args.dt,
        "solvers": {},
        "hard_disabled_low_order": {},
    }
    for solver in (4, 5, 6):
        results = {}
        for enabled, mode in ((False, "exact"), (True, "extrap")):
            label = f"solver{solver}_{mode}"
            results[mode] = run(
                binary,
                root,
                label,
                script_text(enabled=enabled, solver=solver, steps=args.steps, dt=args.dt),
            )
        exact = results["exact"]
        extrap = results["extrap"]
        energy_abs = abs(float(exact["energy_J"]) - float(extrap["energy_J"]))
        report["solvers"][str(solver)] = {
            "exact_wall_s": exact["wall_s"],
            "extrap_wall_s": extrap["wall_s"],
            "speedup": float(exact["wall_s"]) / float(extrap["wall_s"]),
            "energy_abs_error_J": energy_abs,
            "energy_rel_error": energy_abs / max(abs(float(exact["energy_J"])), 1e-30),
            **compare_fields(Path(exact["out"]) / "m000000.ovf", Path(extrap["out"]) / "m000000.ovf"),
        }
    for solver in (2, 3):
        result = run(
            binary,
            root,
            f"solver{solver}_guard",
            script_text(enabled=True, solver=solver, steps=min(args.steps, 20), dt=args.dt),
        )
        report["hard_disabled_low_order"][str(solver)] = {
            "wall_s": result["wall_s"],
            "energy_J": result["energy_J"],
            "exact": result["exact"],
            "extrapolated": result["extrapolated"],
            "status": result["status"],
            "guard_passed": result["extrapolated"] == 0 and "hard-disabled" in str(result["status"]),
        }
    (root / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))
    print(f"artifacts: {root}")


if __name__ == "__main__":
    main()
