// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_bbminimize caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_bbminimize = metal.NewKernel("bbminimize")

// k_bbminimize_async dispatches the Metal implementation of cuda/bbminimize.cu.
func k_bbminimize_async(
	mx unsafe.Pointer,
	my unsafe.Pointer,
	mz unsafe.Pointer,
	m0x unsafe.Pointer,
	m0y unsafe.Pointer,
	m0z unsafe.Pointer,
	tx unsafe.Pointer,
	ty unsafe.Pointer,
	tz unsafe.Pointer,
	nomPartials unsafe.Pointer,
	divPartials unsafe.Pointer,
	slots int,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("bbminimize")
	}

	if mx == nil {
		panic("cuda/metal: kernel bbminimize argument mx must not be nil")
	}
	if my == nil {
		panic("cuda/metal: kernel bbminimize argument my must not be nil")
	}
	if mz == nil {
		panic("cuda/metal: kernel bbminimize argument mz must not be nil")
	}
	if m0x == nil {
		panic("cuda/metal: kernel bbminimize argument m0x must not be nil")
	}
	if m0y == nil {
		panic("cuda/metal: kernel bbminimize argument m0y must not be nil")
	}
	if m0z == nil {
		panic("cuda/metal: kernel bbminimize argument m0z must not be nil")
	}
	if tx == nil {
		panic("cuda/metal: kernel bbminimize argument tx must not be nil")
	}
	if ty == nil {
		panic("cuda/metal: kernel bbminimize argument ty must not be nil")
	}
	if tz == nil {
		panic("cuda/metal: kernel bbminimize argument tz must not be nil")
	}
	if nomPartials == nil {
		panic("cuda/metal: kernel bbminimize argument nomPartials must not be nil")
	}
	if divPartials == nil {
		panic("cuda/metal: kernel bbminimize argument divPartials must not be nil")
	}

	kernel_bbminimize.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(mx),
		metal.BufferArg(my),
		metal.BufferArg(mz),
		metal.BufferArg(m0x),
		metal.BufferArg(m0y),
		metal.BufferArg(m0z),
		metal.BufferArg(tx),
		metal.BufferArg(ty),
		metal.BufferArg(tz),
		metal.BufferArg(nomPartials),
		metal.BufferArg(divPartials),
		metal.I32(slots),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("bbminimize")
	}
}
