// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_cellindices caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_cellindices = metal.NewKernel("cellindices")

// k_cellindices_async dispatches the Metal implementation of cuda/cellindices.cu.
func k_cellindices_async(
	dstx unsafe.Pointer,
	dsty unsafe.Pointer,
	dstz unsafe.Pointer,
	nx float32,
	ny float32,
	nz float32,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("cellindices")
	}

	if dstx == nil {
		panic("cuda/metal: kernel cellindices argument dstx must not be nil")
	}
	if dsty == nil {
		panic("cuda/metal: kernel cellindices argument dsty must not be nil")
	}
	if dstz == nil {
		panic("cuda/metal: kernel cellindices argument dstz must not be nil")
	}

	kernel_cellindices.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dstx),
		metal.BufferArg(dsty),
		metal.BufferArg(dstz),
		metal.F32(nx),
		metal.F32(ny),
		metal.F32(nz),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("cellindices")
	}
}
