// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_copyunpad caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_copyunpad = metal.NewKernel("copyunpad")

// k_copyunpad_async dispatches the Metal implementation of cuda/copyunpad.cu.
func k_copyunpad_async(
	dst unsafe.Pointer,
	Dx int,
	Dy int,
	Dz int,
	src unsafe.Pointer,
	Sx int,
	Sy int,
	Sz int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("copyunpad")
	}

	if dst == nil {
		panic("cuda/metal: kernel copyunpad argument dst must not be nil")
	}
	if src == nil {
		panic("cuda/metal: kernel copyunpad argument src must not be nil")
	}

	kernel_copyunpad.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.I32(Dx),
		metal.I32(Dy),
		metal.I32(Dz),
		metal.BufferArg(src),
		metal.I32(Sx),
		metal.I32(Sy),
		metal.I32(Sz),
	)

	if Synchronous {
		Sync()
		timer.Stop("copyunpad")
	}
}
