// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_pointwise_div caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_pointwise_div = metal.NewKernel("pointwise_div")

// k_pointwise_div_async dispatches the Metal implementation of cuda/div.cu.
func k_pointwise_div_async(
	dst unsafe.Pointer,
	a unsafe.Pointer,
	b unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("pointwise_div")
	}

	if dst == nil {
		panic("cuda/metal: kernel pointwise_div argument dst must not be nil")
	}
	if a == nil {
		panic("cuda/metal: kernel pointwise_div argument a must not be nil")
	}
	if b == nil {
		panic("cuda/metal: kernel pointwise_div argument b must not be nil")
	}

	kernel_pointwise_div.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(a),
		metal.BufferArg(b),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("pointwise_div")
	}
}
