// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_dotproduct caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_dotproduct = metal.NewKernel("dotproduct")

// k_dotproduct_async dispatches the Metal implementation of cuda/dotproduct.cu.
func k_dotproduct_async(
	dst unsafe.Pointer,
	prefactor float32,
	ax unsafe.Pointer,
	ay unsafe.Pointer,
	az unsafe.Pointer,
	bx unsafe.Pointer,
	by unsafe.Pointer,
	bz unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("dotproduct")
	}

	if dst == nil {
		panic("cuda/metal: kernel dotproduct argument dst must not be nil")
	}
	if ax == nil {
		panic("cuda/metal: kernel dotproduct argument ax must not be nil")
	}
	if ay == nil {
		panic("cuda/metal: kernel dotproduct argument ay must not be nil")
	}
	if az == nil {
		panic("cuda/metal: kernel dotproduct argument az must not be nil")
	}
	if bx == nil {
		panic("cuda/metal: kernel dotproduct argument bx must not be nil")
	}
	if by == nil {
		panic("cuda/metal: kernel dotproduct argument by must not be nil")
	}
	if bz == nil {
		panic("cuda/metal: kernel dotproduct argument bz must not be nil")
	}

	kernel_dotproduct.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.F32(prefactor),
		metal.BufferArg(ax),
		metal.BufferArg(ay),
		metal.BufferArg(az),
		metal.BufferArg(bx),
		metal.BufferArg(by),
		metal.BufferArg(bz),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("dotproduct")
	}
}
