// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_exchangedecode caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_exchangedecode = metal.NewKernel("exchangedecode")

// k_exchangedecode_async dispatches the Metal implementation of cuda/exchangedecode.cu.
func k_exchangedecode_async(
	dst unsafe.Pointer,
	aLUT2d unsafe.Pointer,
	regions unsafe.Pointer,
	wx float32,
	wy float32,
	wz float32,
	Nx int,
	Ny int,
	Nz int,
	PBC byte,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("exchangedecode")
	}

	if dst == nil {
		panic("cuda/metal: kernel exchangedecode argument dst must not be nil")
	}
	if aLUT2d == nil {
		panic("cuda/metal: kernel exchangedecode argument aLUT2d must not be nil")
	}
	if regions == nil {
		panic("cuda/metal: kernel exchangedecode argument regions must not be nil")
	}

	kernel_exchangedecode.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(aLUT2d),
		metal.BufferArg(regions),
		metal.F32(wx),
		metal.F32(wy),
		metal.F32(wz),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
		metal.U8(PBC),
	)

	if Synchronous {
		Sync()
		timer.Stop("exchangedecode")
	}
}
