// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_solidanglefourierfield caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_solidanglefourierfield = metal.NewKernel("solidanglefourierfield")

// k_solidanglefourierfield_async dispatches the Metal implementation of cuda/hopfindex-solidangle-fourier-field.cu.
func k_solidanglefourierfield_async(
	fftFx_partial unsafe.Pointer,
	fftFy_partial unsafe.Pointer,
	fftFz_partial unsafe.Pointer,
	fftFx unsafe.Pointer,
	fftFy unsafe.Pointer,
	fftFz unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("solidanglefourierfield")
	}

	if fftFx_partial == nil {
		panic("cuda/metal: kernel solidanglefourierfield argument fftFx_partial must not be nil")
	}
	if fftFy_partial == nil {
		panic("cuda/metal: kernel solidanglefourierfield argument fftFy_partial must not be nil")
	}
	if fftFz_partial == nil {
		panic("cuda/metal: kernel solidanglefourierfield argument fftFz_partial must not be nil")
	}
	if fftFx == nil {
		panic("cuda/metal: kernel solidanglefourierfield argument fftFx must not be nil")
	}
	if fftFy == nil {
		panic("cuda/metal: kernel solidanglefourierfield argument fftFy must not be nil")
	}
	if fftFz == nil {
		panic("cuda/metal: kernel solidanglefourierfield argument fftFz must not be nil")
	}

	kernel_solidanglefourierfield.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(fftFx_partial),
		metal.BufferArg(fftFy_partial),
		metal.BufferArg(fftFz_partial),
		metal.BufferArg(fftFx),
		metal.BufferArg(fftFy),
		metal.BufferArg(fftFz),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
	)

	if Synchronous {
		Sync()
		timer.Stop("solidanglefourierfield")
	}
}
