// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_setvectorpotential caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_setvectorpotential = metal.NewKernel("setvectorpotential")

// k_setvectorpotential_async dispatches the Metal implementation of cuda/hopf-vectorpotential.cu.
func k_setvectorpotential_async(
	Ax unsafe.Pointer,
	Ay unsafe.Pointer,
	Az unsafe.Pointer,
	Fx unsafe.Pointer,
	Fy unsafe.Pointer,
	Fz unsafe.Pointer,
	cy float32,
	Nx int,
	Ny int,
	Nz int,
	PBC byte,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("setvectorpotential")
	}

	if Ax == nil {
		panic("cuda/metal: kernel setvectorpotential argument Ax must not be nil")
	}
	if Ay == nil {
		panic("cuda/metal: kernel setvectorpotential argument Ay must not be nil")
	}
	if Az == nil {
		panic("cuda/metal: kernel setvectorpotential argument Az must not be nil")
	}
	if Fx == nil {
		panic("cuda/metal: kernel setvectorpotential argument Fx must not be nil")
	}
	if Fy == nil {
		panic("cuda/metal: kernel setvectorpotential argument Fy must not be nil")
	}
	if Fz == nil {
		panic("cuda/metal: kernel setvectorpotential argument Fz must not be nil")
	}

	kernel_setvectorpotential.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(Ax),
		metal.BufferArg(Ay),
		metal.BufferArg(Az),
		metal.BufferArg(Fx),
		metal.BufferArg(Fy),
		metal.BufferArg(Fz),
		metal.F32(cy),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
		metal.U8(PBC),
	)

	if Synchronous {
		Sync()
		timer.Stop("setvectorpotential")
	}
}
