// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_solidanglefouriersummand caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_solidanglefouriersummand = metal.NewKernel("solidanglefouriersummand")

// k_solidanglefouriersummand_async dispatches the Metal implementation of cuda/hopfindex-solidangle-fourier-summand.cu.
func k_solidanglefouriersummand_async(
	summand_array unsafe.Pointer,
	FkX_array unsafe.Pointer,
	FkY_array unsafe.Pointer,
	FkZ_array unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("solidanglefouriersummand")
	}

	if summand_array == nil {
		panic("cuda/metal: kernel solidanglefouriersummand argument summand_array must not be nil")
	}
	if FkX_array == nil {
		panic("cuda/metal: kernel solidanglefouriersummand argument FkX_array must not be nil")
	}
	if FkY_array == nil {
		panic("cuda/metal: kernel solidanglefouriersummand argument FkY_array must not be nil")
	}
	if FkZ_array == nil {
		panic("cuda/metal: kernel solidanglefouriersummand argument FkZ_array must not be nil")
	}

	kernel_solidanglefouriersummand.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(summand_array),
		metal.BufferArg(FkX_array),
		metal.BufferArg(FkY_array),
		metal.BufferArg(FkZ_array),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
	)

	if Synchronous {
		Sync()
		timer.Stop("solidanglefouriersummand")
	}
}
