// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_scaleemergentfield caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_scaleemergentfield = metal.NewKernel("scaleemergentfield")

// k_scaleemergentfield_async dispatches the Metal implementation of cuda/hopfindex-solidangle-fourier-scale.cu.
func k_scaleemergentfield_async(
	Fx_scale unsafe.Pointer,
	Fy_scale unsafe.Pointer,
	Fz_scale unsafe.Pointer,
	Fx unsafe.Pointer,
	Fy unsafe.Pointer,
	Fz unsafe.Pointer,
	cx float32,
	cy float32,
	cz float32,
	Nx int,
	Ny int,
	Nz int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("scaleemergentfield")
	}

	if Fx_scale == nil {
		panic("cuda/metal: kernel scaleemergentfield argument Fx_scale must not be nil")
	}
	if Fy_scale == nil {
		panic("cuda/metal: kernel scaleemergentfield argument Fy_scale must not be nil")
	}
	if Fz_scale == nil {
		panic("cuda/metal: kernel scaleemergentfield argument Fz_scale must not be nil")
	}
	if Fx == nil {
		panic("cuda/metal: kernel scaleemergentfield argument Fx must not be nil")
	}
	if Fy == nil {
		panic("cuda/metal: kernel scaleemergentfield argument Fy must not be nil")
	}
	if Fz == nil {
		panic("cuda/metal: kernel scaleemergentfield argument Fz must not be nil")
	}

	kernel_scaleemergentfield.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(Fx_scale),
		metal.BufferArg(Fy_scale),
		metal.BufferArg(Fz_scale),
		metal.BufferArg(Fx),
		metal.BufferArg(Fy),
		metal.BufferArg(Fz),
		metal.F32(cx),
		metal.F32(cy),
		metal.F32(cz),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
	)

	if Synchronous {
		Sync()
		timer.Stop("scaleemergentfield")
	}
}
