// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_kernmulC caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_kernmulC = metal.NewKernel("kernmulC")

// k_kernmulC_async dispatches the Metal implementation of cuda/kernmulc.cu.
func k_kernmulC_async(
	fftM unsafe.Pointer,
	fftK unsafe.Pointer,
	Nx int,
	Ny int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("kernmulC")
	}

	if fftM == nil {
		panic("cuda/metal: kernel kernmulC argument fftM must not be nil")
	}
	if fftK == nil {
		panic("cuda/metal: kernel kernmulC argument fftK must not be nil")
	}

	kernel_kernmulC.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(fftM),
		metal.BufferArg(fftK),
		metal.I32(Nx),
		metal.I32(Ny),
	)

	if Synchronous {
		Sync()
		timer.Stop("kernmulC")
	}
}
