// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_kernmulRSymm2Dz caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_kernmulRSymm2Dz = metal.NewKernel("kernmulRSymm2Dz")

// k_kernmulRSymm2Dz_async dispatches the Metal implementation of cuda/kernmulrsymm2dz.cu.
func k_kernmulRSymm2Dz_async(
	fftMz unsafe.Pointer,
	fftKzz unsafe.Pointer,
	Nx int,
	Ny int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("kernmulRSymm2Dz")
	}

	if fftMz == nil {
		panic("cuda/metal: kernel kernmulRSymm2Dz argument fftMz must not be nil")
	}
	if fftKzz == nil {
		panic("cuda/metal: kernel kernmulRSymm2Dz argument fftKzz must not be nil")
	}

	kernel_kernmulRSymm2Dz.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(fftMz),
		metal.BufferArg(fftKzz),
		metal.I32(Nx),
		metal.I32(Ny),
	)

	if Synchronous {
		Sync()
		timer.Stop("kernmulRSymm2Dz")
	}
}
