// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_kernmulRSymm2Dxy caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_kernmulRSymm2Dxy = metal.NewKernel("kernmulRSymm2Dxy")

// k_kernmulRSymm2Dxy_async dispatches the Metal implementation of cuda/kernmulrsymm2dxy.cu.
func k_kernmulRSymm2Dxy_async(
	fftMx unsafe.Pointer,
	fftMy unsafe.Pointer,
	fftKxx unsafe.Pointer,
	fftKyy unsafe.Pointer,
	fftKxy unsafe.Pointer,
	Nx int,
	Ny int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("kernmulRSymm2Dxy")
	}

	if fftMx == nil {
		panic("cuda/metal: kernel kernmulRSymm2Dxy argument fftMx must not be nil")
	}
	if fftMy == nil {
		panic("cuda/metal: kernel kernmulRSymm2Dxy argument fftMy must not be nil")
	}
	if fftKxx == nil {
		panic("cuda/metal: kernel kernmulRSymm2Dxy argument fftKxx must not be nil")
	}
	if fftKyy == nil {
		panic("cuda/metal: kernel kernmulRSymm2Dxy argument fftKyy must not be nil")
	}
	if fftKxy == nil {
		panic("cuda/metal: kernel kernmulRSymm2Dxy argument fftKxy must not be nil")
	}

	kernel_kernmulRSymm2Dxy.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(fftMx),
		metal.BufferArg(fftMy),
		metal.BufferArg(fftKxx),
		metal.BufferArg(fftKyy),
		metal.BufferArg(fftKxy),
		metal.I32(Nx),
		metal.I32(Ny),
	)

	if Synchronous {
		Sync()
		timer.Stop("kernmulRSymm2Dxy")
	}
}
