// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_kernmulRSymm3D caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_kernmulRSymm3D = metal.NewKernel("kernmulRSymm3D")

// k_kernmulRSymm3D_async dispatches the Metal implementation of cuda/kernmulrsymm3d.cu.
func k_kernmulRSymm3D_async(
	fftMx unsafe.Pointer,
	fftMy unsafe.Pointer,
	fftMz unsafe.Pointer,
	fftKxx unsafe.Pointer,
	fftKyy unsafe.Pointer,
	fftKzz unsafe.Pointer,
	fftKyz unsafe.Pointer,
	fftKxz unsafe.Pointer,
	fftKxy unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("kernmulRSymm3D")
	}

	if fftMx == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftMx must not be nil")
	}
	if fftMy == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftMy must not be nil")
	}
	if fftMz == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftMz must not be nil")
	}
	if fftKxx == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftKxx must not be nil")
	}
	if fftKyy == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftKyy must not be nil")
	}
	if fftKzz == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftKzz must not be nil")
	}
	if fftKyz == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftKyz must not be nil")
	}
	if fftKxz == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftKxz must not be nil")
	}
	if fftKxy == nil {
		panic("cuda/metal: kernel kernmulRSymm3D argument fftKxy must not be nil")
	}

	kernel_kernmulRSymm3D.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(fftMx),
		metal.BufferArg(fftMy),
		metal.BufferArg(fftMz),
		metal.BufferArg(fftKxx),
		metal.BufferArg(fftKyy),
		metal.BufferArg(fftKzz),
		metal.BufferArg(fftKyz),
		metal.BufferArg(fftKxz),
		metal.BufferArg(fftKxy),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
	)

	if Synchronous {
		Sync()
		timer.Stop("kernmulRSymm3D")
	}
}
