// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_llnoprecess caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_llnoprecess = metal.NewKernel("llnoprecess")

// k_llnoprecess_async dispatches the Metal implementation of cuda/llnoprecess.cu.
func k_llnoprecess_async(
	tx unsafe.Pointer,
	ty unsafe.Pointer,
	tz unsafe.Pointer,
	mx unsafe.Pointer,
	my unsafe.Pointer,
	mz unsafe.Pointer,
	hx unsafe.Pointer,
	hy unsafe.Pointer,
	hz unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("llnoprecess")
	}

	if tx == nil {
		panic("cuda/metal: kernel llnoprecess argument tx must not be nil")
	}
	if ty == nil {
		panic("cuda/metal: kernel llnoprecess argument ty must not be nil")
	}
	if tz == nil {
		panic("cuda/metal: kernel llnoprecess argument tz must not be nil")
	}
	if mx == nil {
		panic("cuda/metal: kernel llnoprecess argument mx must not be nil")
	}
	if my == nil {
		panic("cuda/metal: kernel llnoprecess argument my must not be nil")
	}
	if mz == nil {
		panic("cuda/metal: kernel llnoprecess argument mz must not be nil")
	}
	if hx == nil {
		panic("cuda/metal: kernel llnoprecess argument hx must not be nil")
	}
	if hy == nil {
		panic("cuda/metal: kernel llnoprecess argument hy must not be nil")
	}
	if hz == nil {
		panic("cuda/metal: kernel llnoprecess argument hz must not be nil")
	}

	kernel_llnoprecess.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(tx),
		metal.BufferArg(ty),
		metal.BufferArg(tz),
		metal.BufferArg(mx),
		metal.BufferArg(my),
		metal.BufferArg(mz),
		metal.BufferArg(hx),
		metal.BufferArg(hy),
		metal.BufferArg(hz),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("llnoprecess")
	}
}
