// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_madd6 caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_madd6 = metal.NewKernel("madd6")

// k_madd6_async dispatches the Metal implementation of cuda/madd6.cu.
func k_madd6_async(
	dst unsafe.Pointer,
	src1 unsafe.Pointer,
	fac1 float32,
	src2 unsafe.Pointer,
	fac2 float32,
	src3 unsafe.Pointer,
	fac3 float32,
	src4 unsafe.Pointer,
	fac4 float32,
	src5 unsafe.Pointer,
	fac5 float32,
	src6 unsafe.Pointer,
	fac6 float32,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("madd6")
	}

	if dst == nil {
		panic("cuda/metal: kernel madd6 argument dst must not be nil")
	}
	if src1 == nil {
		panic("cuda/metal: kernel madd6 argument src1 must not be nil")
	}
	if src2 == nil {
		panic("cuda/metal: kernel madd6 argument src2 must not be nil")
	}
	if src3 == nil {
		panic("cuda/metal: kernel madd6 argument src3 must not be nil")
	}
	if src4 == nil {
		panic("cuda/metal: kernel madd6 argument src4 must not be nil")
	}
	if src5 == nil {
		panic("cuda/metal: kernel madd6 argument src5 must not be nil")
	}
	if src6 == nil {
		panic("cuda/metal: kernel madd6 argument src6 must not be nil")
	}

	kernel_madd6.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(src1),
		metal.F32(fac1),
		metal.BufferArg(src2),
		metal.F32(fac2),
		metal.BufferArg(src3),
		metal.F32(fac3),
		metal.BufferArg(src4),
		metal.F32(fac4),
		metal.BufferArg(src5),
		metal.F32(fac5),
		metal.BufferArg(src6),
		metal.F32(fac6),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("madd6")
	}
}
