// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_madd2 caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_madd2 = metal.NewKernel("madd2")

// k_madd2_async dispatches the Metal implementation of cuda/madd2.cu.
func k_madd2_async(
	dst unsafe.Pointer,
	src1 unsafe.Pointer,
	fac1 float32,
	src2 unsafe.Pointer,
	fac2 float32,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("madd2")
	}

	if dst == nil {
		panic("cuda/metal: kernel madd2 argument dst must not be nil")
	}
	if src1 == nil {
		panic("cuda/metal: kernel madd2 argument src1 must not be nil")
	}
	if src2 == nil {
		panic("cuda/metal: kernel madd2 argument src2 must not be nil")
	}

	kernel_madd2.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(src1),
		metal.F32(fac1),
		metal.BufferArg(src2),
		metal.F32(fac2),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("madd2")
	}
}
