// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_setmaxangle caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_setmaxangle = metal.NewKernel("setmaxangle")

// k_setmaxangle_async dispatches the Metal implementation of cuda/maxangle.cu.
func k_setmaxangle_async(
	dst unsafe.Pointer,
	mx unsafe.Pointer,
	my unsafe.Pointer,
	mz unsafe.Pointer,
	aLUT2d unsafe.Pointer,
	regions unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	PBC byte,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("setmaxangle")
	}

	if dst == nil {
		panic("cuda/metal: kernel setmaxangle argument dst must not be nil")
	}
	if mx == nil {
		panic("cuda/metal: kernel setmaxangle argument mx must not be nil")
	}
	if my == nil {
		panic("cuda/metal: kernel setmaxangle argument my must not be nil")
	}
	if mz == nil {
		panic("cuda/metal: kernel setmaxangle argument mz must not be nil")
	}
	if aLUT2d == nil {
		panic("cuda/metal: kernel setmaxangle argument aLUT2d must not be nil")
	}
	if regions == nil {
		panic("cuda/metal: kernel setmaxangle argument regions must not be nil")
	}

	kernel_setmaxangle.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(mx),
		metal.BufferArg(my),
		metal.BufferArg(mz),
		metal.BufferArg(aLUT2d),
		metal.BufferArg(regions),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
		metal.U8(PBC),
	)

	if Synchronous {
		Sync()
		timer.Stop("setmaxangle")
	}
}
