// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_minimize caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_minimize = metal.NewKernel("minimize")

// k_minimize_async dispatches the Metal implementation of cuda/minimize.cu.
func k_minimize_async(
	mx unsafe.Pointer,
	my unsafe.Pointer,
	mz unsafe.Pointer,
	m0x unsafe.Pointer,
	m0y unsafe.Pointer,
	m0z unsafe.Pointer,
	tx unsafe.Pointer,
	ty unsafe.Pointer,
	tz unsafe.Pointer,
	dt float32,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("minimize")
	}

	if mx == nil {
		panic("cuda/metal: kernel minimize argument mx must not be nil")
	}
	if my == nil {
		panic("cuda/metal: kernel minimize argument my must not be nil")
	}
	if mz == nil {
		panic("cuda/metal: kernel minimize argument mz must not be nil")
	}
	if m0x == nil {
		panic("cuda/metal: kernel minimize argument m0x must not be nil")
	}
	if m0y == nil {
		panic("cuda/metal: kernel minimize argument m0y must not be nil")
	}
	if m0z == nil {
		panic("cuda/metal: kernel minimize argument m0z must not be nil")
	}
	if tx == nil {
		panic("cuda/metal: kernel minimize argument tx must not be nil")
	}
	if ty == nil {
		panic("cuda/metal: kernel minimize argument ty must not be nil")
	}
	if tz == nil {
		panic("cuda/metal: kernel minimize argument tz must not be nil")
	}

	kernel_minimize.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(mx),
		metal.BufferArg(my),
		metal.BufferArg(mz),
		metal.BufferArg(m0x),
		metal.BufferArg(m0y),
		metal.BufferArg(m0z),
		metal.BufferArg(tx),
		metal.BufferArg(ty),
		metal.BufferArg(tz),
		metal.F32(dt),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("minimize")
	}
}
