// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_mul caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_mul = metal.NewKernel("mul")

// k_mul_async dispatches the Metal implementation of cuda/mul.cu.
func k_mul_async(
	dst unsafe.Pointer,
	a unsafe.Pointer,
	b unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("mul")
	}

	if dst == nil {
		panic("cuda/metal: kernel mul argument dst must not be nil")
	}
	if a == nil {
		panic("cuda/metal: kernel mul argument a must not be nil")
	}
	if b == nil {
		panic("cuda/metal: kernel mul argument b must not be nil")
	}

	kernel_mul.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(a),
		metal.BufferArg(b),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("mul")
	}
}
