// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_normalize caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_normalize = metal.NewKernel("normalize")

// k_normalize_async dispatches the Metal implementation of cuda/normalize.cu.
func k_normalize_async(
	vx unsafe.Pointer,
	vy unsafe.Pointer,
	vz unsafe.Pointer,
	vol unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("normalize")
	}

	if vx == nil {
		panic("cuda/metal: kernel normalize argument vx must not be nil")
	}
	if vy == nil {
		panic("cuda/metal: kernel normalize argument vy must not be nil")
	}
	if vz == nil {
		panic("cuda/metal: kernel normalize argument vz must not be nil")
	}

	var mumaxPointerMask uint32
	if vx != nil {
		mumaxPointerMask |= uint32(1) << 0
	}
	if vy != nil {
		mumaxPointerMask |= uint32(1) << 1
	}
	if vz != nil {
		mumaxPointerMask |= uint32(1) << 2
	}
	if vol != nil {
		mumaxPointerMask |= uint32(1) << 3
	}

	kernel_normalize.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(vx),
		metal.BufferArg(vy),
		metal.BufferArg(vz),
		metal.BufferArg(vol),
		metal.I32(N),
		metal.U32(mumaxPointerMask),
	)

	if Synchronous {
		Sync()
		timer.Stop("normalize")
	}
}
