// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_setPhi caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_setPhi = metal.NewKernel("setPhi")

// k_setPhi_async dispatches the Metal implementation of cuda/phi.cu.
func k_setPhi_async(
	phi unsafe.Pointer,
	mx unsafe.Pointer,
	my unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("setPhi")
	}

	if phi == nil {
		panic("cuda/metal: kernel setPhi argument phi must not be nil")
	}
	if mx == nil {
		panic("cuda/metal: kernel setPhi argument mx must not be nil")
	}
	if my == nil {
		panic("cuda/metal: kernel setPhi argument my must not be nil")
	}

	kernel_setPhi.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(phi),
		metal.BufferArg(mx),
		metal.BufferArg(my),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
	)

	if Synchronous {
		Sync()
		timer.Stop("setPhi")
	}
}
