// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_reducemaxabs caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_reducemaxabs = metal.NewKernel("reducemaxabs")

// k_reducemaxabs_async dispatches the Metal implementation of cuda/reducemaxabs.cu.
func k_reducemaxabs_async(
	src unsafe.Pointer,
	dst unsafe.Pointer,
	initVal float32,
	n int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("reducemaxabs")
	}

	if src == nil {
		panic("cuda/metal: kernel reducemaxabs argument src must not be nil")
	}
	if dst == nil {
		panic("cuda/metal: kernel reducemaxabs argument dst must not be nil")
	}

	kernel_reducemaxabs.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(src),
		metal.BufferArg(dst),
		metal.F32(initVal),
		metal.I32(n),
	)

	if Synchronous {
		Sync()
		timer.Stop("reducemaxabs")
	}
}
