// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_reducemaxvecnorm2 caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_reducemaxvecnorm2 = metal.NewKernel("reducemaxvecnorm2")

// k_reducemaxvecnorm2_async dispatches the Metal implementation of cuda/reducemaxvecnorm2.cu.
func k_reducemaxvecnorm2_async(
	x unsafe.Pointer,
	y unsafe.Pointer,
	z unsafe.Pointer,
	dst unsafe.Pointer,
	initVal float32,
	n int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("reducemaxvecnorm2")
	}

	if x == nil {
		panic("cuda/metal: kernel reducemaxvecnorm2 argument x must not be nil")
	}
	if y == nil {
		panic("cuda/metal: kernel reducemaxvecnorm2 argument y must not be nil")
	}
	if z == nil {
		panic("cuda/metal: kernel reducemaxvecnorm2 argument z must not be nil")
	}
	if dst == nil {
		panic("cuda/metal: kernel reducemaxvecnorm2 argument dst must not be nil")
	}

	kernel_reducemaxvecnorm2.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(x),
		metal.BufferArg(y),
		metal.BufferArg(z),
		metal.BufferArg(dst),
		metal.F32(initVal),
		metal.I32(n),
	)

	if Synchronous {
		Sync()
		timer.Stop("reducemaxvecnorm2")
	}
}
