// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_reducedot caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_reducedot = metal.NewKernel("reducedot")

// k_reducedot_async dispatches the Metal implementation of cuda/reducedot.cu.
func k_reducedot_async(
	x1 unsafe.Pointer,
	x2 unsafe.Pointer,
	dst unsafe.Pointer,
	initVal float32,
	n int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("reducedot")
	}

	if x1 == nil {
		panic("cuda/metal: kernel reducedot argument x1 must not be nil")
	}
	if x2 == nil {
		panic("cuda/metal: kernel reducedot argument x2 must not be nil")
	}
	if dst == nil {
		panic("cuda/metal: kernel reducedot argument dst must not be nil")
	}

	kernel_reducedot.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(x1),
		metal.BufferArg(x2),
		metal.BufferArg(dst),
		metal.F32(initVal),
		metal.I32(n),
	)

	if Synchronous {
		Sync()
		timer.Stop("reducedot")
	}
}
