// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_reducemaxvecdiff2 caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_reducemaxvecdiff2 = metal.NewKernel("reducemaxvecdiff2")

// k_reducemaxvecdiff2_async dispatches the Metal implementation of cuda/reducemaxvecdiff2.cu.
func k_reducemaxvecdiff2_async(
	x1 unsafe.Pointer,
	y1 unsafe.Pointer,
	z1 unsafe.Pointer,
	x2 unsafe.Pointer,
	y2 unsafe.Pointer,
	z2 unsafe.Pointer,
	dst unsafe.Pointer,
	initVal float32,
	n int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("reducemaxvecdiff2")
	}

	if x1 == nil {
		panic("cuda/metal: kernel reducemaxvecdiff2 argument x1 must not be nil")
	}
	if y1 == nil {
		panic("cuda/metal: kernel reducemaxvecdiff2 argument y1 must not be nil")
	}
	if z1 == nil {
		panic("cuda/metal: kernel reducemaxvecdiff2 argument z1 must not be nil")
	}
	if x2 == nil {
		panic("cuda/metal: kernel reducemaxvecdiff2 argument x2 must not be nil")
	}
	if y2 == nil {
		panic("cuda/metal: kernel reducemaxvecdiff2 argument y2 must not be nil")
	}
	if z2 == nil {
		panic("cuda/metal: kernel reducemaxvecdiff2 argument z2 must not be nil")
	}
	if dst == nil {
		panic("cuda/metal: kernel reducemaxvecdiff2 argument dst must not be nil")
	}

	kernel_reducemaxvecdiff2.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(x1),
		metal.BufferArg(y1),
		metal.BufferArg(z1),
		metal.BufferArg(x2),
		metal.BufferArg(y2),
		metal.BufferArg(z2),
		metal.BufferArg(dst),
		metal.F32(initVal),
		metal.I32(n),
	)

	if Synchronous {
		Sync()
		timer.Stop("reducemaxvecdiff2")
	}
}
