// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_regionaddv caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_regionaddv = metal.NewKernel("regionaddv")

// k_regionaddv_async dispatches the Metal implementation of cuda/regionaddv.cu.
func k_regionaddv_async(
	dstx unsafe.Pointer,
	dsty unsafe.Pointer,
	dstz unsafe.Pointer,
	LUTx unsafe.Pointer,
	LUTy unsafe.Pointer,
	LUTz unsafe.Pointer,
	regions unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("regionaddv")
	}

	if dstx == nil {
		panic("cuda/metal: kernel regionaddv argument dstx must not be nil")
	}
	if dsty == nil {
		panic("cuda/metal: kernel regionaddv argument dsty must not be nil")
	}
	if dstz == nil {
		panic("cuda/metal: kernel regionaddv argument dstz must not be nil")
	}
	if LUTx == nil {
		panic("cuda/metal: kernel regionaddv argument LUTx must not be nil")
	}
	if LUTy == nil {
		panic("cuda/metal: kernel regionaddv argument LUTy must not be nil")
	}
	if LUTz == nil {
		panic("cuda/metal: kernel regionaddv argument LUTz must not be nil")
	}
	if regions == nil {
		panic("cuda/metal: kernel regionaddv argument regions must not be nil")
	}

	kernel_regionaddv.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dstx),
		metal.BufferArg(dsty),
		metal.BufferArg(dstz),
		metal.BufferArg(LUTx),
		metal.BufferArg(LUTy),
		metal.BufferArg(LUTz),
		metal.BufferArg(regions),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("regionaddv")
	}
}
