// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_regiondecode caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_regiondecode = metal.NewKernel("regiondecode")

// k_regiondecode_async dispatches the Metal implementation of cuda/regiondecode.cu.
func k_regiondecode_async(
	dst unsafe.Pointer,
	LUT unsafe.Pointer,
	regions unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("regiondecode")
	}

	if dst == nil {
		panic("cuda/metal: kernel regiondecode argument dst must not be nil")
	}
	if LUT == nil {
		panic("cuda/metal: kernel regiondecode argument LUT must not be nil")
	}
	if regions == nil {
		panic("cuda/metal: kernel regiondecode argument regions must not be nil")
	}

	kernel_regiondecode.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(LUT),
		metal.BufferArg(regions),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("regiondecode")
	}
}
