// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_regionselect caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_regionselect = metal.NewKernel("regionselect")

// k_regionselect_async dispatches the Metal implementation of cuda/regionselect.cu.
func k_regionselect_async(
	dst unsafe.Pointer,
	src unsafe.Pointer,
	regions unsafe.Pointer,
	region byte,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("regionselect")
	}

	if dst == nil {
		panic("cuda/metal: kernel regionselect argument dst must not be nil")
	}
	if src == nil {
		panic("cuda/metal: kernel regionselect argument src must not be nil")
	}
	if regions == nil {
		panic("cuda/metal: kernel regionselect argument regions must not be nil")
	}

	kernel_regionselect.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(src),
		metal.BufferArg(regions),
		metal.U8(region),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("regionselect")
	}
}
