// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_shiftbytes caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_shiftbytes = metal.NewKernel("shiftbytes")

// k_shiftbytes_async dispatches the Metal implementation of cuda/shiftbytes.cu.
func k_shiftbytes_async(
	dst unsafe.Pointer,
	src unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	shx int,
	clamp byte,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("shiftbytes")
	}

	if dst == nil {
		panic("cuda/metal: kernel shiftbytes argument dst must not be nil")
	}
	if src == nil {
		panic("cuda/metal: kernel shiftbytes argument src must not be nil")
	}

	kernel_shiftbytes.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(src),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
		metal.I32(shx),
		metal.U8(clamp),
	)

	if Synchronous {
		Sync()
		timer.Stop("shiftbytes")
	}
}
