// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_shiftedgecarryY caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_shiftedgecarryY = metal.NewKernel("shiftedgecarryY")

// k_shiftedgecarryY_async dispatches the Metal implementation of cuda/shiftedgecarryy.cu.
func k_shiftedgecarryY_async(
	dst unsafe.Pointer,
	src unsafe.Pointer,
	othercomp unsafe.Pointer,
	anothercomp unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	shy int,
	clampD float32,
	clampU float32,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("shiftedgecarryY")
	}

	if dst == nil {
		panic("cuda/metal: kernel shiftedgecarryY argument dst must not be nil")
	}
	if src == nil {
		panic("cuda/metal: kernel shiftedgecarryY argument src must not be nil")
	}
	if othercomp == nil {
		panic("cuda/metal: kernel shiftedgecarryY argument othercomp must not be nil")
	}
	if anothercomp == nil {
		panic("cuda/metal: kernel shiftedgecarryY argument anothercomp must not be nil")
	}

	kernel_shiftedgecarryY.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(src),
		metal.BufferArg(othercomp),
		metal.BufferArg(anothercomp),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
		metal.I32(shy),
		metal.F32(clampD),
		metal.F32(clampU),
	)

	if Synchronous {
		Sync()
		timer.Stop("shiftedgecarryY")
	}
}
