// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_shiftedgecarryX caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_shiftedgecarryX = metal.NewKernel("shiftedgecarryX")

// k_shiftedgecarryX_async dispatches the Metal implementation of cuda/shiftedgecarryx.cu.
func k_shiftedgecarryX_async(
	dst unsafe.Pointer,
	src unsafe.Pointer,
	othercomp unsafe.Pointer,
	anothercomp unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	shx int,
	clampL float32,
	clampR float32,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("shiftedgecarryX")
	}

	if dst == nil {
		panic("cuda/metal: kernel shiftedgecarryX argument dst must not be nil")
	}
	if src == nil {
		panic("cuda/metal: kernel shiftedgecarryX argument src must not be nil")
	}
	if othercomp == nil {
		panic("cuda/metal: kernel shiftedgecarryX argument othercomp must not be nil")
	}
	if anothercomp == nil {
		panic("cuda/metal: kernel shiftedgecarryX argument anothercomp must not be nil")
	}

	kernel_shiftedgecarryX.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(src),
		metal.BufferArg(othercomp),
		metal.BufferArg(anothercomp),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
		metal.I32(shx),
		metal.F32(clampL),
		metal.F32(clampR),
	)

	if Synchronous {
		Sync()
		timer.Stop("shiftedgecarryX")
	}
}
