// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_shiftz caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_shiftz = metal.NewKernel("shiftz")

// k_shiftz_async dispatches the Metal implementation of cuda/shiftz.cu.
func k_shiftz_async(
	dst unsafe.Pointer,
	src unsafe.Pointer,
	Nx int,
	Ny int,
	Nz int,
	shz int,
	clampB float32,
	clampF float32,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("shiftz")
	}

	if dst == nil {
		panic("cuda/metal: kernel shiftz argument dst must not be nil")
	}
	if src == nil {
		panic("cuda/metal: kernel shiftz argument src must not be nil")
	}

	kernel_shiftz.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(src),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
		metal.I32(shz),
		metal.F32(clampB),
		metal.F32(clampF),
	)

	if Synchronous {
		Sync()
		timer.Stop("shiftz")
	}
}
