// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_settopologicalchargelattice caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_settopologicalchargelattice = metal.NewKernel("settopologicalchargelattice")

// k_settopologicalchargelattice_async dispatches the Metal implementation of cuda/topologicalcharge-lattice.cu.
func k_settopologicalchargelattice_async(
	s unsafe.Pointer,
	mx unsafe.Pointer,
	my unsafe.Pointer,
	mz unsafe.Pointer,
	icxcy float32,
	Nx int,
	Ny int,
	Nz int,
	PBC byte,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("settopologicalchargelattice")
	}

	if s == nil {
		panic("cuda/metal: kernel settopologicalchargelattice argument s must not be nil")
	}
	if mx == nil {
		panic("cuda/metal: kernel settopologicalchargelattice argument mx must not be nil")
	}
	if my == nil {
		panic("cuda/metal: kernel settopologicalchargelattice argument my must not be nil")
	}
	if mz == nil {
		panic("cuda/metal: kernel settopologicalchargelattice argument mz must not be nil")
	}

	kernel_settopologicalchargelattice.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(s),
		metal.BufferArg(mx),
		metal.BufferArg(my),
		metal.BufferArg(mz),
		metal.F32(icxcy),
		metal.I32(Nx),
		metal.I32(Ny),
		metal.I32(Nz),
		metal.U8(PBC),
	)

	if Synchronous {
		Sync()
		timer.Stop("settopologicalchargelattice")
	}
}
