// Code generated by cuda/metal/cmd/cuda2metal; DO NOT EDIT.
//go:build darwin && arm64

package cuda

import (
	"unsafe"

	"github.com/mumax/3/cuda/metal"
	"github.com/mumax/3/timer"
)

// kernel_zeromaskinv caches the runtime handle so each dispatch skips the kernel-name lookup.
var kernel_zeromaskinv = metal.NewKernel("zeromaskinv")

// k_zeromaskinv_async dispatches the Metal implementation of cuda/zeromaskinv.cu.
func k_zeromaskinv_async(
	dst unsafe.Pointer,
	maskLUT unsafe.Pointer,
	regions unsafe.Pointer,
	N int,
	cfg *config,
) {
	if Synchronous {
		Sync()
		timer.Start("zeromaskinv")
	}

	if dst == nil {
		panic("cuda/metal: kernel zeromaskinv argument dst must not be nil")
	}
	if maskLUT == nil {
		panic("cuda/metal: kernel zeromaskinv argument maskLUT must not be nil")
	}
	if regions == nil {
		panic("cuda/metal: kernel zeromaskinv argument regions must not be nil")
	}

	kernel_zeromaskinv.MustLaunch(metal.GridConfig{
		GridX: uint32(cfg.Grid.X), GridY: uint32(cfg.Grid.Y), GridZ: uint32(cfg.Grid.Z),
		BlockX: uint32(cfg.Block.X), BlockY: uint32(cfg.Block.Y), BlockZ: uint32(cfg.Block.Z),
		ThreadsX: uint32(cfg.Threads.X), ThreadsY: uint32(cfg.Threads.Y), ThreadsZ: uint32(cfg.Threads.Z),
	},
		metal.BufferArg(dst),
		metal.BufferArg(maskLUT),
		metal.BufferArg(regions),
		metal.I32(N),
	)

	if Synchronous {
		Sync()
		timer.Stop("zeromaskinv")
	}
}
